services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: postgres
    env_file: ./.env
    volumes:
      - db:/postgres
    ports:
      - "5432:5432"

  server:
    build: ./server
    container_name: nodejs
    env_file: 
      - ./.env
      - ./server/.env
    ports:
      - "3001:3001"
    depends_on: 
      - db

volumes:
  db: