services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: postgres
    env_file: ./.env
    volumes:
      - db:/postgres

  server:
    build: ./server
    container_name: nodejs
    env_file: ./.env
    ports:
      - "3001:3001"
#    depends_on: db

volumes:
  db: